package com.squalor.consecutor.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

private val DarkColorScheme = darkColorScheme(
    primary = Color(DarkPalette.primary),
    onPrimary = Color(DarkPalette.onPrimary),
    primaryContainer = Color(DarkPalette.primaryContainer),
    onPrimaryContainer = Color(DarkPalette.onPrimaryContainer),
    inversePrimary = Color(DarkPalette.inversePrimary),
    secondary = Color(DarkPalette.secondary),
    onSecondary = Color(DarkPalette.onSecondary),
    secondaryContainer = Color(DarkPalette.secondaryContainer),
    onSecondaryContainer = Color(DarkPalette.onSecondaryContainer),
    tertiary = Color(DarkPalette.tertiary),
    onTertiary = Color(DarkPalette.onTertiary),
    tertiaryContainer = Color(DarkPalette.tertiaryContainer),
    onTertiaryContainer = Color(DarkPalette.onTertiaryContainer),
    background = Color(DarkPalette.background),
    onBackground = Color(DarkPalette.onBackground),
    surface = Color(DarkPalette.surface),
    onSurface = Color(DarkPalette.onSurface),
    surfaceVariant = Color(DarkPalette.surfaceVariant),
    onSurfaceVariant = Color(DarkPalette.onSurfaceVariant),
    surfaceTint = Color(DarkPalette.surfaceTint),
    inverseSurface = Color(DarkPalette.inverseSurface),
    inverseOnSurface = Color(DarkPalette.inverseOnSurface),
    error = Color(DarkPalette.error),
    onError = Color(DarkPalette.onError),
    errorContainer = Color(DarkPalette.errorContainer),
    onErrorContainer = Color(DarkPalette.onErrorContainer),
    outline = Color(DarkPalette.outline),
    outlineVariant = Color(DarkPalette.outlineVariant),
    scrim = Color(DarkPalette.scrim),
    surfaceBright = Color(DarkPalette.surfaceBright),
    surfaceDim = Color(DarkPalette.surfaceDim),
    surfaceContainer = Color(DarkPalette.surfaceContainer),
    surfaceContainerHigh = Color(DarkPalette.surfaceContainerHigh),
    surfaceContainerHighest = Color(DarkPalette.surfaceContainerHighest),
    surfaceContainerLow = Color(DarkPalette.surfaceContainerLow),
    surfaceContainerLowest = Color(DarkPalette.surfaceContainerLowest),
    primaryFixed = Color(DarkPalette.primaryFixed),
    primaryFixedDim = Color(DarkPalette.primaryFixedDim),
    onPrimaryFixed = Color(DarkPalette.onPrimaryFixed),
    onPrimaryFixedVariant = Color(DarkPalette.onPrimaryFixedVariant),
    secondaryFixed = Color(DarkPalette.secondaryFixed),
    secondaryFixedDim = Color(DarkPalette.secondaryFixedDim),
    onSecondaryFixed = Color(DarkPalette.onSecondaryFixed),
    onSecondaryFixedVariant = Color(DarkPalette.onSecondaryFixedVariant),
    tertiaryFixed = Color(DarkPalette.tertiaryFixed),
    tertiaryFixedDim = Color(DarkPalette.tertiaryFixedDim),
    onTertiaryFixed = Color(DarkPalette.onTertiaryFixed),
    onTertiaryFixedVariant = Color(DarkPalette.onTertiaryFixedVariant),
)

private val LightColorScheme = lightColorScheme(
    primary = Color(LightPalette.primary),
    onPrimary = Color(LightPalette.onPrimary),
    primaryContainer = Color(LightPalette.primaryContainer),
    onPrimaryContainer = Color(LightPalette.onPrimaryContainer),
    inversePrimary = Color(LightPalette.inversePrimary),
    secondary = Color(LightPalette.secondary),
    onSecondary = Color(LightPalette.onSecondary),
    secondaryContainer = Color(LightPalette.secondaryContainer),
    onSecondaryContainer = Color(LightPalette.onSecondaryContainer),
    tertiary = Color(LightPalette.tertiary),
    onTertiary = Color(LightPalette.onTertiary),
    tertiaryContainer = Color(LightPalette.tertiaryContainer),
    onTertiaryContainer = Color(LightPalette.onTertiaryContainer),
    background = Color(LightPalette.background),
    onBackground = Color(LightPalette.onBackground),
    surface = Color(LightPalette.surface),
    onSurface = Color(LightPalette.onSurface),
    surfaceVariant = Color(LightPalette.surfaceVariant),
    onSurfaceVariant = Color(LightPalette.onSurfaceVariant),
    surfaceTint = Color(LightPalette.surfaceTint),
    inverseSurface = Color(LightPalette.inverseSurface),
    inverseOnSurface = Color(LightPalette.inverseOnSurface),
    error = Color(LightPalette.error),
    onError = Color(LightPalette.onError),
    errorContainer = Color(LightPalette.errorContainer),
    onErrorContainer = Color(LightPalette.onErrorContainer),
    outline = Color(LightPalette.outline),
    outlineVariant = Color(LightPalette.outlineVariant),
    scrim = Color(LightPalette.scrim),
    surfaceBright = Color(LightPalette.surfaceBright),
    surfaceDim = Color(LightPalette.surfaceDim),
    surfaceContainer = Color(LightPalette.surfaceContainer),
    surfaceContainerHigh = Color(LightPalette.surfaceContainerHigh),
    surfaceContainerHighest = Color(LightPalette.surfaceContainerHighest),
    surfaceContainerLow = Color(LightPalette.surfaceContainerLow),
    surfaceContainerLowest = Color(LightPalette.surfaceContainerLowest),
    primaryFixed = Color(LightPalette.primaryFixed),
    primaryFixedDim = Color(LightPalette.primaryFixedDim),
    onPrimaryFixed = Color(LightPalette.onPrimaryFixed),
    onPrimaryFixedVariant = Color(LightPalette.onPrimaryFixedVariant),
    secondaryFixed = Color(LightPalette.secondaryFixed),
    secondaryFixedDim = Color(LightPalette.secondaryFixedDim),
    onSecondaryFixed = Color(LightPalette.onSecondaryFixed),
    onSecondaryFixedVariant = Color(LightPalette.onSecondaryFixedVariant),
    tertiaryFixed = Color(LightPalette.tertiaryFixed),
    tertiaryFixedDim = Color(LightPalette.tertiaryFixedDim),
    onTertiaryFixed = Color(LightPalette.onTertiaryFixed),
    onTertiaryFixedVariant = Color(LightPalette.onTertiaryFixedVariant),
)

@Composable
fun ConsecutorTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = if (isSystemInDarkTheme()) DarkColorScheme else LightColorScheme,
        typography = Typography(),
        content = content
    )
}
